server:
  port: 8080
spring:
  application:
    name: web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: password123
    sql-script-encoding: utf-8
    initialization-mode: ALWAYS
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  #    hibernate:
  #      naming:
  #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
logging:
  file:
    name: "/qiwen/log/web.log"
  level:
    root: info
    com:
      mac:
        scp:
          mapper: debug
  pattern:
    #    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldYellow(%thread) | %boldGreen(%logger) | %msg%n"
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) | %highlight(%thread) | %replace(%caller{1}){'at| |\t|Caller.{1}0|\r|\n', ''} %highlight(%msg) %n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} = [%thread] = %-5level = %logger{50} - %msg%n"
  config:

mybatis-plus:
  type-aliases-package: com.mac.scp.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false