spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/temp_db/file;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: h2
    password:
    platform: h2
  h2:
    console:
      enabled: true
logging:
  level:
    com:
      mac:
        common:
          exception: debug
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
file:
  store:
    path: D:\abc\
server:
  port: 18080