server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
spring:
  application:
    name: web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: password123
    data: classpath:database/data.sql
    sql-script-encoding: utf-8
    initialization-mode: ALWAYS
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled: true
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    name: "/qiwen/log/web.log"
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldYellow(%thread) | %boldGreen(%logger) | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} = [%thread] = %-5level = %logger{50} - %msg%n"
mybatis:
  type-aliases-package: com.mac.scp.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml